[system]

max_grad          =     24 # [mT/m]
max_slew          =    35 # [T/m/s]
grad_raster_time  =  10e-6 # [s]
rf_raster_time    =   1e-6 # [s]
rf_ringdown_time  =  10e-6 # [s]
rf_dead_time      = 200e-6 # [s]
adc_dead_time     =  10e-6 # [s]

[spiral]

contrast     = 'trueFISP' # FLASH or FISP
slew_ratio   = 0.7  # How much of the system slew rate to be used for spiral design.  
ro_duration = 3.0e-3 # [s] Readout duration
adc_dwell   = 1e-6 # [s]
arm_ordering = 'ga' #_custom' # 'linear', 'ga', 'tinyga', 'linear_custom'
GA_steps    = 144  # 0 to disable GA
GA_angle    = 222.4969    # [deg]
grad_rew_method = "ext_trap_area"
rewinder_time = 0.65e-3
custom_order = [0, 16, 8, 4, 20, 12, 2, 18, 10, 6, 14, 1, 17, 9, 5, 13, 3, 19, 11, 7, 15]
#custom_order = [0, 8, 4, 12, 2, 10, 6, 14, 1, 9, 5, 13, 3, 11, 7, 15 ] # Custom ordering of the arms determined by 0-indexed interleave number. Only enabled if arm_ordering='linear_custom'
# Note: custom_order assumes the number of interleaves, and does not work if it does not match.

[acquisition]

resolution      = 2       # [mm]
fov             = [24]  # [cm]
slice_thickness = 8       # [mm]
flip_angle      = 70 #degrees
rf_duration     = 0.5e-3  # [s]
tbwp            = 2

TR              = 0     # [ms], 0 for min TR
TE              = 0     # [ms], 0 for min TE

repetitions     = 1 

[acquisition.fa_schedule]
type = "ramp_ibrahim"
enabled = false 
T1                = 701 # [ms]
T2                = 58  # [ms] 

[[preparations]]
# we should turn this OFF for cine style, as the script handles this.
type = "trigger"
enabled = false 
trigger_type = "physio1" # can be physio1 or physio2 (siemens lingo)
 
[[preparations]]
type             = "tagging"
enabled          = false 
tag_type         = "grid"
grid_tag_spacing = 1   # [cm]
include_in_filename = true

# tag_type        = "radial"
# num_tags = 10  # Number of taglines per half circle
# tagging_time = 10  # in ms

[[preparations]]
type            = "rf"
enabled         = false 
phase           = 180    # degrees
rf_scale        = 0.5    # scale alpha by 0.5
TR_scale        = 0.5    # set delay to TR/2

 
[[end_preparations]]
type            = "rf"
enabled         = false 
phase           = 0      # degrees
rf_scale        = -1    # -1 implies use the last RF amplitude.
TR_scale        = 0.5    # set delay to TR/2


[[end_preparations]]
type            = "rf"
enabled         = false 
phase           = 180    # degrees
rf_scale        = -0.5    # scale alpha by 0.5
TR_scale        = 0      # set delay

[[end_preparations]]
type            = "crusher"
enabled         = false 
channel         = "z"
cycles_per_thickness = 4

[user_settings]

write_seq    = true
filename_ext = 'freemax' # This will be attached to the filename
show_plots   = true 
detailed_rep = true
